version: '3'

services:
  mysqlsrv:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "eventdb"
    ports:
      - "3307:3306"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
